// Pool PRONTA de temas para os mini-contos "Cá em Casa" (limites no dia a dia).
// A Vivianne escolhe e gera. O ↻ IA só acrescenta mais.

export const TOPICOS_BANDA: string[] = [
  'O telefonema da mãe que nunca acaba',
  'Dizer "não" a um convite sem dar mil desculpas',
  'Deixar o Rui ajudar na cozinha (aprender a receber)',
  'A avó que comenta o prato da Nina ao jantar',
  'O Tó que aprende a dizer "não quero"',
  'Recusar fazer horas extra outra vez',
  'Quando a mãe pede dinheiro emprestado de novo',
  '"Na minha casa não se respondia aos pais"',
  'A Nina que pede desculpa por existir',
  'Quando alguém invade o teu tempo de descanso',
  'O almoço de família onde todos opinam sobre a tua vida',
  'Devolver uma tarefa que não era tua',
  'O grupo de família no telemóvel a explodir',
  'Quando dizes "estou bem" e não estás',
  'A Teresa que faz tudo por todos e desaparece',
  'Pôr limite a um comentário sobre o corpo do Tó',
  'Sair de uma conversa que te magoa',
  'Quando a avó compara os netos',
  'Aceitar um elogio sem o desfazer',
  'A culpa de descansar enquanto há roupa para passar',
  'Quando alguém conta um segredo teu',
  'Dizer "isso magoou-me" em vez de engolir',
  'Não atender o telefone às 23h',
  'A Nina que assume a raiva da mãe como sua',
  'Quando te pedem para escolher entre dois familiares',
  'Deixar o filho errar sem corrigir tudo',
  '"Faz isto por mim, és a única que pode"',
  'Marcar uma hora só tua ao domingo',
  'Quando o silêncio à mesa diz tudo',
  'Honrar a avó sem viver a vida dela',
];
