// Pools PRONTAS de temas de reels, por formato. A Vivianne escolhe e gera —
// não tem de inventar nada. O ↻ IA só ACRESCENTA mais a estas.
// Âmbito: psicologia transpessoal · constelação familiar · espiritualidade ·
// desenvolvimento pessoal e profissional.

export const TOPICOS_REELS: Record<string, string[]> = {
  sinais: [
    'Sinais de parentificação',
    'Sinais de lealdades invisíveis',
    'Sinais de que estás a viver a vida dos teus pais',
    'Sinais de burnout emocional',
    'Sinais de que não aprendeste a receber',
    'Sinais de que carregas uma exclusão familiar',
    'Sinais de uma criança parentificada (já adulta)',
    'Sinais de que dizes sim por medo',
    'Sinais de culpa herdada',
    'Sinais de que te identificaste com alguém excluído do clã',
    'Sinais de limites frágeis',
    'Sinais de hiper-responsabilidade',
    'Sinais de que assumes um papel que não é teu',
    'Sinais de fuga espiritual (spiritual bypassing)',
    'Sinais de que confundes amor com sacrifício',
    'Sinais de auto-abandono',
    'Sinais de não-pertença',
    'Sinais de fidelidade ao sofrimento familiar',
    'Sinais de que precisas de pôr um limite',
    'Sinais de que vives em alerta',
    'Sinais de luto não elaborado no sistema',
    'Sinais de que repetes o destino de um antepassado',
    'Sinais de que dás de mais e ficas vazia',
    'Sinais de sombra projetada nos outros',
    'Sinais de cansaço de quem cuida',
    'Sinais de que o teu "não" foi silenciado na infância',
    'Sinais de vínculo ansioso',
    'Sinais de que o corpo guarda o que a mente cala',
    'Sinais de que estás pronta para uma travessia interior',
    'Sinais de despertar espiritual',
  ],
  ninguem: [
    'Porque é que repetimos os padrões dos nossos pais',
    'O que ninguém te explica sobre a culpa',
    'Porque é que algumas pessoas nunca saem da pobreza (leitura sistémica)',
    'O que ninguém te explica sobre dizer "não"',
    'Porque é que atraímos sempre o mesmo tipo de relação',
    'O que ninguém te explica sobre o sucesso que não se sustenta',
    'Porque é que sabotamos o que mais queremos',
    'O que ninguém te explica sobre as lealdades invisíveis',
    'Porque é que cuidar demais adoece',
    'O que ninguém te explica sobre a sombra',
    'Porque é que o filho mais "forte" é o mais sobrecarregado',
    'O que ninguém te explica sobre dar e receber',
    'Porque é que o dinheiro também obedece a ordens familiares',
    'O que ninguém te explica sobre o sintoma (ele tem sentido)',
    'Porque é que excluir alguém da família nos custa a todos',
    'O que ninguém te explica sobre a espiritualidade que foge da dor',
    'Porque é que o que rejeitamos nos outros vive em nós',
    'O que ninguém te explica sobre o vazio',
    'Porque é que pertencer pesa mais do que ser feliz',
    'O que ninguém te explica sobre o perdão',
    'Porque é que adiar a tua vida é uma forma de lealdade',
    'O que ninguém te explica sobre os limites',
    'Porque é que a infância continua a decidir por nós',
    'O que ninguém te explica sobre o amor maduro',
    'Porque é que precisamos de honrar quem veio antes',
  ],
  pergunta: [
    'Qual foi a frase da tua infância que ainda vive dentro de ti?',
    'O que é que tu carregas que nunca foi teu?',
    'A quem é que ainda tentas provar o teu valor?',
    'Qual é o "não" que mais te custa dizer?',
    'O que é que a tua família nunca falou em voz alta?',
    'Que parte de ti aprendeste a esconder para seres amada?',
    'O que farias se não tivesses medo de desiludir?',
    'Qual é o padrão que juraste não repetir… e repetiste?',
    'O que é que ainda não te deixas receber?',
    'Que lugar ocupas na tua família — e qual era para ser o teu?',
    'O que é que o teu cansaço está a tentar dizer-te?',
    'Quem é que tu honras quando sofres?',
    'O que pesa mais: pertencer ou ser tu?',
    'Qual é a verdade que evitas há anos?',
    'O que precisarias de soltar para respirar fundo hoje?',
    'Que herança emocional queres que acabe em ti?',
    'O que chamas de amor mas talvez seja medo?',
    'Onde dás de mais e recebes de menos?',
    'Que sonho adiaste para cuidar dos outros?',
    'O que dirias hoje à criança que foste?',
  ],
  glossario: [
    'Sombra', 'Ego', 'Self', 'Arquétipo', 'Individuação', 'Inconsciente coletivo',
    'Persona', 'Anima e Animus', 'Sincronicidade', 'Complexo', 'Projeção', 'Numinoso',
    'Campo morfogenético', 'Ordens do Amor', 'Lealdade invisível', 'Pertença',
    'Parentificação', 'Substituição de papéis', 'Consciência do clã', 'Psyché (alma)',
    'Logos (sentido)', 'Transcendência', 'Imanência', 'Noite escura da alma',
    'Experiência de pico', 'Mandala', 'Símbolo', 'Mito pessoal', 'Presença',
    'Vazio fértil', 'Bypassing espiritual', 'Autocompaixão', 'Limite (fronteira)', 'Resiliência',
  ],
  pensador: [
    'Uma ideia de Jung: a sombra',
    'Uma ideia de Jung: a individuação',
    'Uma ideia de Jung: o inconsciente coletivo',
    'Uma ideia de Jung: o que resistes, persiste',
    'Uma ideia de Jung: a segunda metade da vida',
    'Uma ideia de Viktor Frankl: o sentido na dor',
    'Uma ideia de Frankl: a última das liberdades humanas',
    'Uma ideia de Frankl: quem tem um porquê suporta quase todo o como',
    'Uma ideia de Bert Hellinger: as Ordens do Amor',
    'Uma ideia de Hellinger: o direito de pertencer',
    'Uma ideia de Hellinger: tomar os pais como são',
    'Uma ideia de Hellinger: o sintoma como amor cego',
    'Uma ideia de Rumi: a ferida é por onde entra a luz',
    'Uma ideia de Joseph Campbell: a jornada do herói',
    'Uma ideia de Campbell: segue a tua felicidade',
    'Uma ideia de Ram Dass: estar aqui agora',
    'Uma ideia de Maslow: as experiências de pico',
    'Uma ideia de Maslow: a autorrealização',
    'Uma ideia de Winnicott: a mãe suficientemente boa',
    'Uma ideia de Bowlby: a vinculação',
    'Uma ideia de Carl Rogers: a aceitação incondicional',
    'Uma ideia de Thich Nhat Hanh: a respiração consciente',
    'Uma ideia de Ken Wilber: integrar corpo, mente e espírito',
    'Uma ideia de Jung: a função transcendente',
    'Uma ideia de Rumi: sê uma lâmpada para os outros',
  ],
};

export function topicosReels(formatoId: string): string[] {
  return TOPICOS_REELS[formatoId] ?? [];
}
