// Os cursos (pos-graduacoes) da Vivianne — dimensao DIDATICA dos infograficos
// (substitui os universos da loja nesta linha; sem CTA, so conhecimento).
import type { Mundo } from '@/lib/estudio-conteudo';

export type Curso = {
  id: string;
  nome: string;
  descricao: string;
  mundo: Mundo;       // paleta visual
  conceitos: string[]; // conceitos didaticos sugeridos (das disciplinas)
};

export const CURSOS: Curso[] = [
  {
    id: 'transpessoal',
    nome: 'Psicologia Transpessoal',
    descricao: 'Bio · psíquico · social · espiritual. Oriente e Ocidente em diálogo.',
    mundo: 'escola',
    conceitos: [
      'Bio-psico-social-espiritual',
      'Oriente encontra Ocidente',
      'Arquétipos e símbolos (Jung)',
      'Regressão e memória',
      'A mandala como mapa interno',
      'Estados ampliados de consciência',
      'O Self transpessoal',
      'Sombra e integração',
      'Experiências de pico (Maslow)',
      'O inconsciente coletivo',
      'Símbolo, mito e cura',
      'Persona e máscara social',
      'Anima e Animus',
      'Sincronicidade',
      'A função transcendente',
      'Individuação',
      'Complexos psíquicos',
      'Projeção da sombra',
      'O numinoso',
      'Espiritualidade e neurociência',
      'Consciência e atenção plena',
      'O ego ao serviço do Self',
      'Crise como abertura (emergência espiritual)',
      'Sonhos como mensagens',
      'O herói interior e a jornada',
      'Morte e renascimento simbólicos',
      'Respiração e estados de consciência',
      'Meditação e o cérebro',
      'O corpo como porta da psique',
      'Integrar luz e sombra',
    ],
  },
  {
    id: 'constelacao',
    nome: 'Constelação Familiar Sistémica',
    descricao: 'Bert Hellinger e as Ordens do Amor. A pessoa dentro dos seus sistemas.',
    mundo: 'synchim',
    conceitos: [
      'As Ordens do Amor',
      'O direito de pertencer',
      'A ordem: quem veio primeiro',
      'Dar e receber em equilíbrio',
      'Lealdades invisíveis',
      'Substituição de papéis',
      'Identificar-se com um excluído',
      'O campo morfogenético',
      'Parentificação: ser mãe da mãe',
      'A consciência do clã',
      'Tomar os pais como são',
      'O sintoma como amor',
      'Amor cego vs amor consciente',
      'Os excluídos do sistema',
      'Segredos de família',
      'Filhos de substituição',
      'O peso dos não-nascidos (abortos, perdas)',
      'Honrar quem veio antes',
      'A força que vem dos pais',
      'Casais: o equilíbrio entre dar e tomar',
      'Lugar dos filhos vs lugar do casal',
      'Movimento interrompido em direção à mãe',
      'Destinos repetidos no sistema',
      'Pertencer ao preço de adoecer',
      'A boa consciência e a má consciência',
      'Inclusão: dar lugar a quem foi esquecido',
      'A reverência diante do destino',
      'O que pertence a cada um voltar a cada um',
      'Frases que curam (frases de solução)',
      'Hierarquia entre família de origem e atual',
    ],
  },
  {
    id: 'espiritualidade',
    nome: 'Psicologia e Espiritualidade',
    descricao: 'Espiritualidade como sentido, propósito e qualidade de vida.',
    mundo: 'autora',
    conceitos: [
      'Espiritualidade não é religião',
      'Sentido e propósito (Frankl)',
      'Niilismo e o vazio',
      'Bem-estar espiritual',
      'Espiritualidade na clínica',
      'Emoções e autoconhecimento',
      'A noite escura da alma',
      'Logoterapia: o porquê',
      'Práticas contemplativas',
      'Religiosidade e desenvolvimento',
      'Os três caminhos de sentido (Frankl)',
      'Sofrimento com sentido',
      'Bypassing espiritual (a fuga disfarçada)',
      'Fé, esperança e cura',
      'Gratidão como prática',
      'Perdão: libertar-se, não esquecer',
      'Aceitação vs resignação',
      'Transcender o ego',
      'O sagrado no quotidiano',
      'Silêncio e escuta interior',
      'Rituais de passagem',
      'Morte como mestra da vida',
      'Compaixão e autocompaixão',
      'Conexão: comigo, com o outro, com o todo',
      'Valores como bússola',
      'Crise existencial e renascimento',
      'Mindfulness e presença',
      'A pergunta pelo sentido da vida',
      'Espiritualidade e saúde mental',
      'Esperança que não nega a dor',
    ],
  },
  {
    id: 'desenvolvimento',
    nome: 'Desenvolvimento Pessoal e Profissional',
    descricao: 'Cadeira comum aos 3: carreira, comunicação e saúde do cuidador.',
    mundo: 'infonte',
    conceitos: [
      'Inteligência emocional',
      'Burnout do cuidador',
      'Comunicar com presença',
      'Saúde mental de quem cuida',
      'Liderança que cuida',
      'Limites saudáveis',
      'Escuta ativa',
      'Autocompaixão',
      'Propósito profissional',
      'Dizer não sem culpa',
      'Assertividade vs agressividade',
      'Gestão do tempo e da energia',
      'O custo de agradar a todos',
      'Fronteiras entre trabalho e vida',
      'Pedir ajuda é força',
      'Feedback que constrói',
      'Hábitos e mudança sustentável',
      'Procrastinação e medo',
      'Foco numa era de distração',
      'Confiança e autoestima',
      'Lidar com o erro e a frustração',
      'Empatia sem te perderes no outro',
      'Conversas difíceis',
      'Descanso como produtividade',
      'Síndrome do impostor',
      'Motivação intrínseca',
      'Resiliência no trabalho',
      'Cuidar de quem cuida (equipas)',
      'Sentido e vocação',
    ],
  },
];

export function getCurso(id: string): Curso {
  return CURSOS.find((c) => c.id === id) ?? CURSOS[0];
}
